/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Add2fa: typeof import('./src/components/add2fa.vue')['default']
    DragAndDropUpload: typeof import('./src/components/DragAndDropUpload.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    FillTheInfo: typeof import('./src/components/FillTheInfo.vue')['default']
    ShowCode: typeof import('./src/components/ShowCode.vue')['default']
  }
}
